name: build.yml
on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']
  workflow_dispatch:
jobs:
  build_maps:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # - copy code below to release.yml -
      - uses: actions/checkout@v4
      - name: Install base dependencies
        run: |
          sudo apt update
          sudo apt -y install smpq parallel
      - name: Build
        run: |
          ./build_release_package.sh
      - name: zip
        run: |
         pushd target
         zip -r ../Archipelago-SC2Data.zip .
         popd
      - name: Push Artifacts
        uses: actions/upload-artifact@v4
        with:
          # Name of the artifact to upload.
          # Optional. Default is 'artifact'
          name: Archipelago-SC2Data

          # A file, directory or wildcard pattern that describes what to upload
          # Required.
          path: Archipelago-SC2Data.zip
          retention-days: 7
      - name: Deploy-Legacy-repo
        # Remove me after AP releases with the organization repo used
        if: ${{ github.ref == 'refs/heads/master' && github.repository_owner == 'Ziktofel' }}
        uses: WebFreak001/deploy-nightly@v3.1.0
        with:
          # find out this value by opening https://api.github.com/repos/<owner>/<repo>/releases in your browser and copy the full "upload_url" value including the {?name,label} part
          upload_url: https://uploads.github.com/repos/Ziktofel/Archipelago-SC2-data/releases/165307117/assets{?name,label}
          release_id: 165307117 # API4
          asset_path: ./Archipelago-SC2Data.zip
          asset_name: Archipelago-SC2Data.zip
          asset_content_type: application/zip
      - name: Deploy
        if: ${{ github.ref == 'refs/heads/master' && github.repository_owner == 'archipelago-sc2' }}
        uses: WebFreak001/deploy-nightly@v3.1.0
        with:
          # find out this value by opening https://api.github.com/repos/<owner>/<repo>/releases in your browser and copy the full "upload_url" value including the {?name,label} part
          upload_url: https://uploads.github.com/repos/archipelago-sc2/Archipelago-SC2-data/releases/261895427/assets{?name,label}
          release_id: 261895427 # API4
          asset_path: ./Archipelago-SC2Data.zip
          asset_name: Archipelago-SC2Data.zip
          asset_content_type: application/zip
